apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-rbd
