apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
spec:
  selector:
    app: jupyterlab
    release: {{ .Release.Name }}
  ports:
    - name: tcp8888
      protocol: TCP
      port: 8888
      targetPort: 8888
