apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: {{ .Values.subdomain | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-svc
          servicePort: 8888
